apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver-container
          image: your-webserver-image:tag
          ports:
            - containerPort: 80
          volumeMounts:
            - name: efs-persistent-storage
              mountPath: /efs-mount-path
      volumes:
        - name: efs-persistent-storage
          persistentVolumeClaim:
            claimName: efs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: my-namespace
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
